<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
        <PackageReference Include="FluentResults"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CC.Shared.Domain\CC.Shared.Domain.csproj" />
    </ItemGroup>
</Project>
