// <auto-generated />
using System;
using System.Collections.Generic;
using CC.PractitionerService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CC.PractitionerService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CC.PractitionerService.Domain.Practitioners.PractitionerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "CC.PractitionerService.Domain.Practitioners.PractitionerProfile.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("text")
                                .HasColumnName("patronymic");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("surname");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhotoUrl", "CC.PractitionerService.Domain.Practitioners.PractitionerProfile.PhotoUrl#PhotoUrl", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("photo_url");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Specializations", "CC.PractitionerService.Domain.Practitioners.PractitionerProfile.Specializations#PractitionerSpecializations", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<int[]>("AgeGroups")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("specializations_age_groups");

                            b1.PrimitiveCollection<int[]>("Languages")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("specializations_languages");

                            b1.PrimitiveCollection<int[]>("ProblemAreas")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("specializations_problem_areas");
                        });

                    b.HasKey("Id")
                        .HasName("pk_practitioner_profiles");

                    b.ToTable("practitioner_profiles", (string)null);
                });

            modelBuilder.Entity("CC.PractitionerService.Domain.WorkSchedules.Adjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_schedule_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "CC.PractitionerService.Domain.WorkSchedules.Adjustment.Period#DateTimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("From")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("period_from");

                            b1.Property<DateTime>("To")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("period_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_adjustments");

                    b.ToTable("adjustments", (string)null);
                });

            modelBuilder.Entity("CC.PractitionerService.Domain.WorkSchedules.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("_timeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Recurrences", "CC.PractitionerService.Domain.WorkSchedules.WorkSchedule.Recurrences#WeeklyRecurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Day");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TimeRange", "CC.PractitionerService.Domain.WorkSchedules.WorkSchedule.Recurrences#WeeklyRecurrence.TimeRange#TimeRange", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<TimeOnly>("From");

                                    b2.Property<TimeOnly>("To");
                                });

                            b1.ToJson("recurrences");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SessionDuration", "CC.PractitionerService.Domain.WorkSchedules.WorkSchedule.SessionDuration#SessionDuration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("Value")
                                .HasColumnType("interval")
                                .HasColumnName("session_duration");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ValidityPeriod", "CC.PractitionerService.Domain.WorkSchedules.WorkSchedule.ValidityPeriod#WorkScheduleValidityPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("validity_period_from");

                            b1.Property<DateOnly?>("To")
                                .HasColumnType("date")
                                .HasColumnName("validity_period_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_work_schedules");

                    b.ToTable("work_schedules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
