// <auto-generated />
using CC.HandbookService.Infrastructure;
using CC.HandbookService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CC.HandbookService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("HandbookItemSequence");

            modelBuilder.Entity("CC.HandbookService.Domain.Handbooks.HandbookItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"HandbookItemSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("CC.HandbookService.Domain.Handbooks.AgeGroup", b =>
                {
                    b.HasBaseType("CC.HandbookService.Domain.Handbooks.HandbookItem");

                    b.ToTable("age_groups", (string)null);
                });

            modelBuilder.Entity("CC.HandbookService.Domain.Handbooks.Language", b =>
                {
                    b.HasBaseType("CC.HandbookService.Domain.Handbooks.HandbookItem");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("CC.HandbookService.Domain.Handbooks.ProblemArea", b =>
                {
                    b.HasBaseType("CC.HandbookService.Domain.Handbooks.HandbookItem");

                    b.ToTable("problem_areas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
