// <auto-generated />
using System;
using System.Collections.Generic;
using CC.TechSupportService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CC.TechSupportService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260429190503_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tech_support")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.FileDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<long>("ContentSize")
                        .HasColumnType("bigint")
                        .HasColumnName("content_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_path");

                    b.HasKey("Id")
                        .HasName("pk_files_details");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_files_details_attachment_id");

                    b.ToTable("files_details", "tech_support");
                });

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CsatComment")
                        .HasColumnType("text")
                        .HasColumnName("csat_comment");

                    b.Property<byte?>("CsatRating")
                        .HasColumnType("smallint")
                        .HasColumnName("csat_rating");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FirstRespondedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_responded_at");

                    b.Property<DateTime?>("LastUserRespondedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_user_responded_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime>("SlaFirstResponseAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sla_first_response_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<int>("TicketCategory")
                        .HasMaxLength(32)
                        .HasColumnType("integer")
                        .HasColumnName("ticket_category");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RelatedEntity", "CC.TechSupportService.Domain.Entities.Ticket.RelatedEntity#RelatedEntity", b1 =>
                        {
                            b1.Property<Guid>("RelatedEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("related_entity_related_entity_id");

                            b1.Property<string>("RelatedType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("related_entity_related_type");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Reporter", "CC.TechSupportService.Domain.Entities.Ticket.Reporter#Reporter", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("ReporterId")
                                .HasColumnType("uuid")
                                .HasColumnName("reporter_reporter_id");

                            b1.Property<string>("ReporterType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("reporter_reporter_type");
                        });

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasAlternateKey("Number")
                        .HasName("ak_tickets_number");

                    b.ToTable("tickets", "tech_support");
                });

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_attachments");

                    b.ToTable("ticket_attachments", "tech_support");
                });

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Author", "CC.TechSupportService.Domain.Entities.TicketComment.Author#Author", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("author_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("author_type");
                        });

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.ToTable("ticket_comments", "tech_support");
                });

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_histories");

                    b.ToTable("ticket_histories", "tech_support");
                });

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.UserRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("AmountOfRequestForLastHour")
                        .HasColumnType("smallint")
                        .HasColumnName("amount_of_request_for_last_hour");

                    b.Property<DateTime>("LastRequestTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_request_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_users_request");

                    b.ToTable("users_request", "tech_support");
                });

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.FileDetails", b =>
                {
                    b.HasOne("CC.TechSupportService.Domain.Entities.TicketAttachment", null)
                        .WithMany("FileDetails")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_files_details_ticket_attachments_attachment_id");
                });

            modelBuilder.Entity("CC.TechSupportService.Domain.Entities.TicketAttachment", b =>
                {
                    b.Navigation("FileDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
