// <auto-generated />
using System;
using System.Collections.Generic;
using CC.AppointmentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CC.AppointmentService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260318204030_AddColumnUrlAppointments")]
    partial class AddColumnUrlAppointments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CC.AppointmentService.Domain.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ClientSnapshot", "CC.AppointmentService.Domain.Appointments.Appointment.ClientSnapshot#ClientSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "CC.AppointmentService.Domain.Appointments.Appointment.ClientSnapshot#ClientSnapshot.FullName#FullName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Patronymic");

                                    b2.Property<string>("Surname")
                                        .IsRequired();
                                });

                            b1.ToJson("client_snapshot");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PractitionerSnapshot", "CC.AppointmentService.Domain.Appointments.Appointment.PractitionerSnapshot#PractitionerSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "CC.AppointmentService.Domain.Appointments.Appointment.PractitionerSnapshot#PractitionerSnapshot.FullName#FullName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Patronymic");

                                    b2.Property<string>("Surname")
                                        .IsRequired();
                                });

                            b1.ToJson("practitioner_snapshot");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TimeSlot", "CC.AppointmentService.Domain.Appointments.Appointment.TimeSlot#DateTimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("From")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("time_slot_from");

                            b1.Property<DateTime>("To")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("time_slot_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.ToTable("appointments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
