// <auto-generated />
using System;
using CC.NotificationService.Domain;
using CC.NotificationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CC.NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CC.NotificationService.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<NotificationPayload>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CC.NotificationService.Domain.Notification", b =>
                {
                    b.OwnsMany("CC.NotificationService.Domain.NotificationChannel", "Channels", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid")
                                .HasColumnName("notification_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Error")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("error");

                            b1.Property<DateTime?>("SentAt")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("sent_at");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("NotificationId", "Id")
                                .HasName("pk_notification_channel");

                            b1.ToTable("notification_channel", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NotificationId")
                                .HasConstraintName("fk_notification_channel_notifications_notification_id");
                        });

                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
